const express = require("express")
const app=express()
app.use(express.json())
app.use(express.urlencoded({ extended:true}))
app.use(express.static("public"))
const complaintRoutes=require("./routes/complaintRoutes")
app.use(complaintRoutes)
app.get("/",(req,res)=>{
    res.send("Server is running")
})
app.listen(3000)